#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="daed"
PROG="/usr/bin/daed"

cleanup_netns() {
	if [ -e "/run/netns/daens" ]; then
		logger -t daed "Cleaning up residual netns 'daens'..."
		ip netns del daens 2>/dev/null
		rm -f /run/netns/daens 2>/dev/null
	fi
}

start_service() {
	config_load "$CONF"

	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1

	cleanup_netns

	local listen_addr web_root config_dir
	config_get listen_addr "config" "listen_addr" "0.0.0.0:2023"
	config_get web_root "config" "web_root" "/usr/share/daed/web"
	config_get config_dir "config" "config_dir" "/etc/daed/"

	mkdir -p "${config_dir}"

	procd_open_instance "$CONF"
	procd_set_param command "$PROG" run
	procd_append_param command --config "${config_dir}"
	procd_append_param command --listen "$listen_addr"
	procd_append_param command --web-root "$web_root"

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param respawn
	procd_set_param stderr 1

	procd_close_instance
}

stop_service() {
	procd_kill "$CONF" ""
	cleanup_netns
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}
